version: '3.9'
services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: "dz1"
      POSTGRES_USER: "dz1user"
      POSTGRES_PASSWORD: "pgdz1pswrd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - post-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dz1user -d dz1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - zd1network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dz1user@kek.com"
      PGADMIN_DEFAULT_PASSWORD: "pgdz1pswrd"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - zd1network

  application:
    build: /core
    ports:
      - 8000:80
    networks:
      - zd1network
    depends_on:
      - postgres
      - pgadmin

volumes:
  post-data:
  pgadmin-data:


networks:
  zd1network:
    driver: bridge
